# Generated by Django 4.2.11 on 2024-04-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("detailing_type", models.CharField(max_length=20)),
                ("data", models.JSONField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
